"""
slap.py - Slap Module
Copyright 2009, Michael Yanovich, yanovich.net

http://willie.dftba.net
"""

import random
import re
from willie.module import commands


@commands('slap')
def slap(willie, trigger):
    """.slap <target> - Slaps <target>"""
    text = trigger.group().split()
    if len(text) < 2:
        text.append(trigger.nick)
    text[1] = re.sub(r"\x1f|\x02|\x12|\x0f|\x16|\x03(?:\d{1,2}(?:,\d{1,2})?)?", '', text[1])
    if text[1].startswith('#'):
        return
    if text[1] == 'me' or text[1] == 'myself':
        text[1] = trigger.nick
    if text[1] == willie.nick:
        if (trigger.nick not in willie.config.admins):
            text[1] = trigger.nick
        else:
            text[1] = 'itself'
    if text[1] in willie.config.admins:
        if (trigger.nick not in willie.config.admins):
            text[1] = trigger.nick
    slap = ['throws a keyboard at {}',
'beautifies {} with some knuckle duster imprints',
'sends hordes of lemmings over {}',
'slaps {} around with a pink Macintosh',
'slaps {} around with nuclear waste',
'throws a playstation at {}',
'slaps {} around a bit with a small Imperial-Class Stardestroyer',
'slaps {} about with a large Fluffy Donkey.',
'slaps {} about with a damp womble',
'punches {} in da ribs',
'grabs {}\'s hair and rips it out by the roots',
'drives {} across the head with a bus',
'kicks {} where the sun don\'t shine',
'shoves a large pencil up {}\'s nose.',
'slaps {} around a bit with a large lightbulb.',
'grabs {}\'s large buttocks and rips them off with his bare hands.',
'slaps {} across the face with a large bald rabbit',
'slaps {} up a bit',
'grabs {} by his feet and chucks him out of the window',
'slaps {} about a lot with a large snotty hankie',
'slaps {} about with a golf club',
'slaps {} about with a dead mole',
'slaps {} in the face with a damp crustacean',
'slaps {} about with {} with {} with {} with {} witttttttthhhhhhh........',
'slaps {} in the face',
'shooves a large goat up {}\'s ass',
'throws himself at {}',
'grabs {} and sits on him then slowly lets out his noxious gases',
'relieves himself over {}',
'blasts {} apart with his womble launcher',
'smacks {} in her face',
'slaps {} across the head with a hairy toothbrush',
'slaps {} about with a squashed frog',
'whacks {} in the face with a hedgehog',
'grabs {}\'s legs and breaks them',
'slaps {} about with a squashed frog',
'chucks a cream cake at {}',
'rides a rhino into {}',
'grabs the aluminum bat from the house and runs out to practice baseball with {}\'s head...whoops!...WHACK!!.. Now {}\'s pea-sized brain is all over the field! RETARDO!',
'shoves {} off the nearest cliff',
'smashes a wine bottle over {}\'s head',
'slaps {} with a lil sweet kitten --- ahhh 8D',
'grabs his chainsaw off his shelf, steps up to {} and slowly, so slowly, cuts off his thick neck, letting the blood spew from his arteries, covering $me in the warm liquid',
'picks up his watermellon and smashes it over {}\'s head',
'plays tiddlewinks with {}\'s teeth',
'rips out {}\'s eyeballs and eats them --- mmmmmmm',
'grabs his ice hockey stick and deftly slices off {}\'s legs',
'pushes {} into a large food blender',
'shoves a hamster into {}\'s mouth and slams his jaws together !',
'rides a monster truck over {}',
'wedgies {} !!!!! OUCH !!!',
'locks {} in a freezer and swallows the key :)',
'thoughs a fake left punch at {} , while at the same time, pulling out his samari sword and, swinging it through the air, slices off {}\'s ears',
'drops an elephant onto {}',
'chucks {} into a pit full of crocodiles',
'rips open {}\'s gut and pulls out his intestines',
'is ignoring {}',
'farts in {}\'s face',
'pours man eating antz over {}',
'picks {} up and chucks him in a bath of boiling hot oil',
'gives {} a lobotomy',
'slices {}\'s scalp off and starts chewing on his brain',
'slaps {} about a bit with a small tadpole',
'slaps {} around with a large whale',
'throws {} into a volcano',
'blasts {} apart with his Enhanced Shock Rifle',
'blows {} apart with his "phat" cow launcher',
'chucks cowpats at {}',
'showers {} with sparkling jellyfish',
'blows {} away with his bad breath',
'takes one look at {} and is sick all over the floor',
'slaps {} about a bit with a mouldy sandwich',
'throws a box of feathers at {}',
'slaps {} about with his knuckle dusters',
'whacks {} in the face with an anaconda',
'shoves {} up a tree',
'gives {} a box of chocolates',
'cuts {} into little pieces, puts his bits in envelopes and posts them to antartica',
'grabs {} and shooves him in a wheely bin',
'grabs {}\'s head and rips it off. Then with all his will power, summons the belch monster within, and spews his dinner down {}\'s neck',
'slaps {} with a reeally FAT CAT - meeeoooowwwww !!!',
'purrs at {} ;)',
'chucks a concrete cricket ball at {}\'s head',
'hurls a hurlbat at {}',
'laughs at the way {} snorts when he laughs',
'slaps {} silly with a snotty tissue',
'blows {} apart with his marble launcher',
'kicks {} in the balls --- ooo thats GOTTA HURT !!!',
'gives {} a lump of C4',
'fires 50 pence pieces at {}',
'fires {} at the Sun',
'gives {} a lift to pyscholand',
'locks {} in a mental institute',
'runs away from {}\'s hairy arse',
'hits {} on the head with a large toilet',
'slaps {} silly with a urinal',
'slaps {} about a bit with some baguettes',
'uses {} s a wicket',
'sues {} for being so ugly',
'waxes {}\'s legs',
'waxes {}\'s groin',
'chucks several obese Americans on {}',
'SCREAMS LOUDLY AT {}',
'humps {}',
'slaps {} about a lot with his little pink handbag',
'Laughs Out Loud at {}\'s orange and pink hair',
'slaps {} about a bit with a lump of mercury',
'grinds down {}\'s fingers down to stubs with a meat grinder',
'covers {} in sheep skin and sets his wolf after him',
'pushes {} infront of a thousand stampeding buffalo',
'lobs a hand grenade at {} and ducks',
'cuts {} up and feeds him to a penguin',
'puts some screws through {}\'s eyeballs',
'sniggers at {}',
'chuckles at {}\'s fat ass',
'gives {} a hate bite',
'pulls out {}\'s teeth with a knife and fork',
'eats {}\'s ears for dinner',
'plays football with {}\'s large head',
'breaks both of {}\'s kneecaps, then puts a box of chocolates out of his reach :)',
'throws {} into Hell - "Naughty Girl !"',
'gives {} a @3-->---',
'breaks {} in half',
'rips out {}\'s heart',
'glares evilly at {}',
'punches {} so hard it punctures his chest and goes through the other side !!',
'pokes {} up the nose with a pair of chopsticks !!',
'n00bifies {}',
'slaps {} about with a fat Leprechaun',
'drowns {} in a cup of water!',
'slaps {} about with a giant boob!',
'telefrags {}',
'throws a bookcase at {}',
'slaps {} in the face with a large tree',
'brands "n00b" on {}\'s forehead',
'kicks {} in the face',
'flicks ear wax at {}',
'sticks {}\'s fingers in a plug socket',
'tips puts {}\'s feet in cement and throws him into the sea',
'laughs at {}\'s high heels',
'flicks cds at {} and accidently slices off {}\'s fingers',
'bites off {}\'s ear',
'slices {}\'s throat with a woodpecker',
'chucks aftershave in {}\'s eyes',
'shaves off {}\'s eyebrows while {} is asleep',
'whups {}\'s ass at UT',
'blows up {}\'s pet dog',
'sets a rabid dog upon {}',
'sends {}\'s photo to the police as a "Wanted" person',
'chucks {} in a bath of scorpions',
'laughs like a cheap whore... and starts to ponder his sexuality !!',
'smiles at {} .. thinking - bet your glad i\'m not feeling trigger happy today {} :)',
'slaps {} around a bit with a small trout',
'feeds {} to the sharks',
'throws {} off a bridge',
'grabs {}, ties him down, and waxes his ARSE !!! OUCH !!!',
'puts a plastic bag over {}\'s head and smiles wickedly as {} gasps for air',
'slaps {} about with his monitor',
'tapes {} to a skateboard and pushes him down a hill towards an oncoming bus',
'flushes {} down a toilet',
'grabs {}\'s hands and slaps them down on a red hot cooker',
'pushes {} into a microwave and hits the cook button !',
'stuffs his face full of chocolate',
'shoves a hairdrier up {}\'s nose and turns it up to "nose melter" setting',
'chases after {} with a weed whacker....hey you need a haircut!',
'kicks {} off his feet onto his knees; KNEEL BEFORE YOUR MASTER !!',
'gets out his brand new bat and knocks {} around a lot',
'pulls out his bubble gum, chews on it a bit, ponders over the meaning of {}, then walks away.........',
'slaps {} with a lil fishy wishy',
'steals {}\'s cookies. muhahahahaha!',
'falls off his chair from laughter and spills coffee all over the fookin keyboard !!',
'slaps {} about with a large lampost',
'grabs a handful of cockroaches and shoves them down {}\'s pants',
'pushes {} into a bath full of maggots',
'slaps {} about with an old smelly sock',
'slaps {} about with a toupee',
'chucks {} into a large cement mixer with a camel',
'slaps {} about with his pet camel',
'slaps {} about a bit with an orchestra',
'opens {}\'s gob and chucks a hand grenade down his throat and ducks',
'breaks {}\'s elbow',
'slaps {} about with a fat gay telletubbie',
'pokes {} in the belly button',
'slaps {} about a lot with a fat mongoose',
'strips {} naked and then throws pins at him',
'slaps {} about some with a skinny mongoose',
'pulls out {}\'s armpit hair !!',
'blasts {} apart with a fat spud gun !!!',
'throws {} into a pit of fat belly dancers',
'breaks {}\'s nose with a green spondge lampost',
'kicks his fat rabbit at {}',
'rips out his hair in his frustration at {} !!',
'puts {} in an oven',
'pulls out {}\'s lungs through his throat !',
'wonders why {} has such a fat arse',
'slaps {} about with a trout, yes thats right, a fucking TROUT !! u got a fucking problem with my trout ? hey ? WELL !! HAVE U !!! TOUGH !!!!!!!!!!!!!!',
'feeds {} to a hungry pack of dolphins',
'suffocates {} with a large condom',
'blasts {} apart with his mobile phone radiation emitter',
'throws {} infront of an oncoming train',
'gives {} skydiving lessons without a parachute',
'locks {} in a suntaning bed',
'cuts open {}\'s chest then pours salt all over it',
'feeds {} to the ants',
'drowns {} in his own vomit',
'slaps {} silly with an abominable snowman',
'slaps {} about a bit with a fat elephant',
'chucks pins at {}',
'gives {} acupuncture with some large tent pegs',
'gives {} a whole lot of new orafices by practising his knife throwing skills with {}',
'drops a ton of bricks on {}\'s head',
'puts {} into a Spanish bull ring',
'pulls out {}\'s tongue ring violently',
'engraves his name on {}\'s eyeballs',
'slaps {} about a bit with an old granny',
'slaps {} about a lot with 2 small eskimos',
'slaps {} silly with the Titanic',
'gets down on one knee and asks: "Will you marry me {}?"',
'hands {} some spikey dildos',
'assaults {} with a pepper',
'assaults {} with a dildo',
'assaults {} with a cabbage',
'assaults {} with a whistle',
'puts {} in a jar full of bees',
'performs the round-house kick to {}\'s face']
    
    try:
        message = random.choice(slap)
        bot.action (slap.format(text[1])
    except Exception as e:
	bot.say('You boke it now. Hope you are happy, %s!' % trigger.nick)
